name: Run Backend on Schedule or Button Push

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/20 16-23,0-3 * * *" # Every 20 minutes from 8 AM - 8 PM PT (16:00 - 03:59 UTC)
  #   - cron: "0 4-15 * * *" # Every hour from 8 PM - 8 AM PT (04:00 - 15:59 UTC)

jobs:
  run-backend:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Run Backend Script
        env:
          GDRIVE_CRED: ${{ secrets.GDRIVE_CRED }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd backend
          source image_rec.sh
