name: Run Backend on Button Push

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  run-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13" # Python 3.13 is unstable; 3.10 is recommended

      - name: Setup Virtual Environment
        run: |
          cd backend
          python -m venv ENV
          source ENV/bin/activate
          pip install -r requirements.txt
        shell: bash

      - name: Run input.py with Secret
        env:
          GDRIVE_CRED: ${{ secrets.GDRIVE_CRED }}
        run: |
          python input.py
        shell: bash

      - name: Print Changed Files
        run: |
          git status --short
        shell: bash
