name: Run Backend on Button Push

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  run-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        working-directory: backend
        run: |
          python -m venv ENV
          ENV/bin/pip install -r requirements.txt

      - name: Run input.py with Secret
        working-directory: backend
        env:
          GDRIVE_CRED: ${{ secrets.GDRIVE_CRED }}
        run: ENV/bin/python input.py

      - name: Print Changed Files
        run: echo "Listing all files in backend/gdrive_images/:"
          ls -R backend/gdrive_images/
