name: Run Backend on Button Push

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  run-backend:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Run Backend Script
        env:
          GDRIVE_CRED: ${{ secrets.GDRIVE_CRED }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd backend
          source image_rec.sh
